#!/usr/bin/env bash

#=== SH_SCRIPT  ================================================================
#         NAME:   Force-XDG
#  DESCRIPTION:   A BASH script to force XDG paths for programs polluting HOME.
#         DATE:   2022/07/07
#       AUTHOR:   @Polirritmico https://github.com/polirritmico
#===============================================================================


#=== LICENSE ===================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You can receive a copy of the GNU General Public License at
# <https://www.gnu.org/licenses/>. 
#
#===============================================================================

# e - script stops on error (any internal or external return !=0)
# u - error if undefined variable
# o pipefail - script fails if one of piped command fails
# x - output each line (debug)
set -euo pipefail


#-----------------------------------------------------------------------
#  Global settings
#-----------------------------------------------------------------------
SCRIPT_VERSION="1.3"
SHORT_DESCRIPTION="A BASH script to force XDG paths for programs polluting HOME."
SCRIPT_NAME="Force-XDG"

FORCE_XDG_FOLDER="$XDG_DATA_HOME"/"$SCRIPT_NAME"
FAKE_HOME_FOLDER="$FORCE_XDG_FOLDER/fake_home"

DEPENDENCIES=( "mapfile" "read" "getopts" "sed" "grep" "diff" "sort"\
               "basename" "readlink" "tput" )
# Get the real script filename even through a symbolic link
SCRIPT_RUN="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

#----------------------------------------
# Terminal output font styles and colors
GREEN="\033[0;32m"
ORANGE="\033[0;33m"
NS="\033[0m" # No color
BLD="\e[1m"  # Bold text style
ITL="\e[3m"  # Italic text style

F_OK="${GREEN}${BLD}OK${NS}"
F_APP="${ORANGE}"
F_ERR="\e[0;31m"
F_CMD="\033[1;36m"
F_ARG="\033[1;32m"
F_OPT="\033[1;32m"
F_SCR="\033[1;36m\e[1m${SCRIPT_RUN}:${NS} "
F_WAR="\033[0;33m\e[3m"


#-----------------------------------------------------------------------
# Check dependencies
#-----------------------------------------------------------------------
missing_deps=0
for dependency in "${DEPENDENCIES[@]}"; do
    if ! command -v "$dependency" > /dev/null 2>&1 ; then
        echo -e "$F_ERR$SCRIPT_RUN: Could't find '$dependency' on the system."\
                "Check if is installed.$NS" >&2
        ((++missing_deps))
    fi
done
if [[ $missing_deps -gt 0 ]]; then
    exit 1
fi



#===  FUNCTION  ================================================================
#         NAME:   Version
#  DESCRIPTION:   Show script name, script version and short description.
#===============================================================================
function version()
{
    echo -e "$BLD$SCRIPT_NAME v$SCRIPT_VERSION$NS"
    echo -e "$ITL$SHORT_DESCRIPTION$NS\n"

}  # ------------  end of function version  ------------



#===  FUNCTION  ================================================================
#         NAME:   Help
#  DESCRIPTION:   Show the script usage and documentation help.
#===============================================================================
function help()
{
    echo -e "${BLD}Usage: $F_CMD$SCRIPT_RUN ${F_ARG}[OPTION]... [PROGRAM]$NS
       $F_CMD$SCRIPT_RUN ${F_ARG}[OPTION]... [PROGRAM] [PROGRAM ARGS]$NS

Move hidden polluting files from [HOME] to [XDG_DATA_HOME]/${SCRIPT_NAME}/ folder.
When [PROGRAM] is run for the first time is STRONGLY RECOMMENDED to close it
immediately to get a clean file list. The script compare the state of [HOME]
before and after the first execution to make a folders and files list based on
the changes.

${BLD}Options:
$F_OPT  -c (custom)      ${NS}Change the program identifier to a custom one. Usefull
                   when launching programs from scripts or when the same
                   program could be initialized from differents symlinks
                   or paths.
$F_OPT  -d (dir)         ${NS}Manually set ${SCRIPT_NAME} data dir
                   ($ITL$FORCE_XDG_FOLDER$NS by default)
$F_OPT  -f (fake)        ${NS}Enable fake \$HOME mode.
$F_OPT  -h (help)        ${NS}Display this help message.
$F_OPT  -v (version)     ${NS}Display the version of $SCRIPT_NAME and exit."

}  # ------------  end of function help  ------------



#-------------------------------------------------------------------------------
#  Global variables
#-------------------------------------------------------------------------------

custom_dir=""
custom_id=""
fake_home_mode=false

apps_db=()
apps_db_file="$FORCE_XDG_FOLDER"/db
app_name_raw=""
app_name=""
app_args=""
app_dirs_and_files=()
home_before=""
home_after=""


#-------------------------------------------------------------------------------
#  Handle command line arguments
#-------------------------------------------------------------------------------
while getopts ":hvc:d:f" opt
    do
        case $opt in
            h)
                version
                help
                exit 0
                ;;
            v)
                version
                exit 0
                ;;
            c)
                custom_id=$OPTARG
                ;;
            d)
                custom_dir=$OPTARG
                ;;
            f)
                fake_home_mode=true
                ;;
            :)
                echo -e "$F_ERR$SCRIPT_NAME: Invalid option: '-$OPTARG'" \
                        "requires an argument. Check '-help'.$NS" >&2
                exit 1
                ;;
            *)
                echo -e "$F_ERR$SCRIPT_NAME: Invalid option: '-$OPTARG'." \
                        "Check '-help'.$NS" >&2
                exit 1
                ;;
    esac
done
shift $((OPTIND-1))

#----------------------------------------
# Check and update global vars

# Check arguments
if [[ $# -eq 0 ]]; then
    echo -e "${F_ERR}$SCRIPT_RUN: Error: Missing arguments." \
            "Check '${SCRIPT_RUN} -help'.$NS" >&2
    exit 1
fi

# Get app name
app_name_raw=$1
if [[ -n $custom_id ]]; then # -n: not empty
    app_name="$custom_id"
else
    app_name="${app_name_raw##*/}" # remove path
fi

# Check if passed app exist on the system
if ! command -v "$app_name_raw" > /dev/null 2>&1; then
    echo -e "$F_ERR$SCRIPT_RUN: ERROR: Could't find '$app_name_raw'" \
            "on the system.$NS" >&1
    exit 1
fi

# Get all args after program (>$1)
app_args=("${*:2}")

# Check custom dir and fake_home_mode at the same time
if [[ -n ${custom_dir} && ${fake_home_mode} == true ]]; then
    echo -e "$F_ERR$SCRIPT_RUN:" \
            "ERROR: Can't use custom dir with fake mode enabled.$NS"
    exit 1
# Use custom dir if setted
elif [[ -n ${custom_dir} ]]; then
    FORCE_XDG_FOLDER="${custom_dir}"
    apps_db_file="$FORCE_XDG_FOLDER"/db
fi

# Output helper for echo (appname with format)
F_APP="${F_APP}${app_name}$NS$ITL"



#===  FUNCTION  ================================================================
#         NAME:   Get dir and files from db
#  DESCRIPTION:   Read the db file and get dirs and files used by appname or
#                 set the fake home mode.
#===============================================================================
function get_dir_and_files_from_db()
{
    echo -en "${F_SCR}${ITL}Retrieving data of '${F_APP}' in the db:$NS "
    if [[ ! -e $apps_db_file ]]; then
        echo -e "\n${F_SCR}${F_WAR}No db file found.$NS"
        return
    fi
    echo -e "$F_OK"

    # Get apps_db_file content into an array
    mapfile -t apps_db < <(cat "$apps_db_file")

    for (( i=0; i<${#apps_db[@]}; i++ )); do
        # Split line with ";" into an array
        IFS=";" read -r -a line <<< "${apps_db[$i]}"

        if [[ ${line[0]} == "$app_name" ]]; then
            # Get the array without first entry (app_name)
            app_dirs_and_files=("${line[@]:1}")
            break
        fi
    done

    if [[ ${#app_dirs_and_files[@]} -eq 0 ]]; then
        echo -e "${F_SCR}${F_WAR}No data found.$NS"
    elif [[ ${app_dirs_and_files[0]} == "FAKEHOME" ]]; then
        fake_home_mode=true
    fi

}  # ------------  end of function get_dir_and_files_from_db  ------------



#===  FUNCTION  ================================================================
#         NAME:   Get home diff list
#  DESCRIPTION:   Compare the before and after list and get the dirs and files
#                 created by the app into app_dirs_and_files variable. Also
#                 remove non dot files/folders and '$HOME/.' from each path.
#                 If there's no new folders or files, exit the script.
#===============================================================================
function get_home_diff_list()
{
    echo -en "${F_SCR}${ITL}Getting hidden dirs/files created in HOME...$NS "

    local differences=""
    # Get only diff entries between home_before and home_after
    differences=$(diff --changed-group-format='%>' --unchanged-group-format=''\
                  <(echo -e "$home_before") <(echo -e "$home_after") || true)
    if [[ -z "$differences" ]]; then
        echo -e "\n$F_SCR${ITL}No new dirs or files detected. Nothing to do."
        echo -e "$F_SCR${ITL}Closing...$NS"
        exit
    fi

    # Remove non dot folders/files
    differences=$(grep "$HOME/\." <<< "$differences")
    # Remove $HOME/. from the path of each entry
    differences=${differences//$HOME\/\./}
    # Convert into an array
    mapfile -t app_dirs_and_files <<< "$differences"

    echo -e "$F_OK"
    echo -en "${F_SCR}${ITL}Obtained elements: $NS"
    for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
        echo -en "${BLD}'${app_dirs_and_files[i]}' "
    done
    echo -e "$NS"

}  # ------------  end of function get_home_diff_list  ------------



#===  FUNCTION  ================================================================
#         NAME:   Get HOME folders and files list
#  DESCRIPTION:   Returns the current list of folders and files in HOME.
#===============================================================================
function get_home_folders_and_files_list()
{
    find "$HOME" -mindepth 1 -maxdepth 1

}  # ------------  end of function get_home_folders_and_files_list  ------------



#===  FUNCTION  ================================================================
#         NAME:   Interruption handler
#  DESCRIPTION:   Run when 'Ctrl+C' is detected while running the command.
#===============================================================================
function interruption_handler()
{
    local sep_char="="
    local max_line_length=""
    if [[ -z $TERM || $TERM == "dumb" ]]; then
        max_line_length=1
    else
        max_line_length=$(tput cols)
    fi
    local output=""
    for (( i=0; i<max_line_length; i++ )); do
        output="${output}${sep_char}"
    done
    echo -e "\n${GREEN}${output}${NS}"

    echo -e "$F_SCR${F_ERR}Exiting on signal SIGINT:" \
            "'${F_APP}${F_ERR}' terminated.$NS"
    mv_dirs_and_files_from_home
    echo -e "$F_SCR${ITL}Closing...$NS"
    exit

}  # ------------  end of function interruption_handler  ------------





#===  FUNCTION  ================================================================
#         NAME:   Make data folder
#  DESCRIPTION:   If FORCE_XDG_FOLDER doesn't exist create it.
#===============================================================================
function make_data_folder()
{
    if [[ ! -d "$FORCE_XDG_FOLDER" ]]; then
        echo -en "${F_SCR}Creating"\
                 "'$ORANGE$FORCE_XDG_FOLDER$NS$ITL' folder... "
        mkdir -p "$FORCE_XDG_FOLDER"
        echo -e "$F_OK"
    fi

}  # ------------  end of function make_data_folder  ------------



#===  FUNCTION  ================================================================
#         NAME:   Mv dirs and files from home
#  DESCRIPTION:   Move dirs and files in the db from $HOME to XDG wrapper dir.
#===============================================================================
function mv_dirs_and_files_from_home()
{
    echo -en "${F_SCR}${ITL}Cleaning home...$NS "
    # Create dir if doesn't exists
    if [[ ! -d "${FORCE_XDG_FOLDER}/${app_name}" ]]; then
        echo -en "\n${F_SCR}${ITL}and creating target folder: '$F_APP'$NS "
        mkdir "${FORCE_XDG_FOLDER}/${app_name}"
    fi

    # Move the dirs and files
    for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
        local file=${app_dirs_and_files[i]}
        mv "$HOME/.$file" "${FORCE_XDG_FOLDER}/$app_name/$file"
    done
    echo -e "$F_OK"

}  # ------------  end of function mv_dirs_and_files_from_home  ------------



#===  FUNCTION  ================================================================
#         NAME:   Move dirs and files to home
#  DESCRIPTION:   Move dirs and files readed from the db to Home.
#===============================================================================
function mv_dirs_and_files_to_home()
{
    echo -en "${F_SCR}${ITL}Moving '${F_APP}' folders to home..."
    # First check if any folder/file already exist to prevent data loss
    for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
        local file=${app_dirs_and_files[i]}
        if [[ -e "${HOME}/.${file}" ]]; then
            echo -e "\n$F_ERR${SCRIPT_RUN}:$NS ${F_ERR}Error: '$file'"\
                    "already exist in home folder.$NS" >&2
            exit 1
        fi
    done
    # Now we move the files and folders
    for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
        local file=${app_dirs_and_files[i]}
        mv "${FORCE_XDG_FOLDER}/${app_name}/${file}" "${HOME}/.${file}"
    done
    echo -e " $F_OK"

}  # ------------  end of function mv_dirs_and_files_to_home  ------------



#===  FUNCTION  ================================================================
#         NAME:   Run app
#  DESCRIPTION:   Get appname command with args and run it
#===============================================================================
function run_app()
{
    if [[ -z ${app_args[0]} ]]; then
        app_command="${ORANGE}${app_name_raw}${NS}${ITL}"
    else
        app_command="${ORANGE}${app_name_raw} ${app_args}${NS}${ITL}"
    fi
    echo -e "${F_SCR}${ITL}Running '${app_command}':$NS"
    separator "${app_name}"

    eval " $app_name_raw $app_args"

    separator
    echo -e "${F_SCR}${ITL}Closed '${F_APP}'$NS"

}  # ------------  end of function run_app  ------------



#===  FUNCTION  ================================================================
#         NAME:   Save app info into db
#  DESCRIPTION:   Save the appname, dirs and folders (data) into the database.
#===============================================================================
function save_app_info_into_db()
{
    echo -e "${F_SCR}${ITL}Storing '${F_APP}' info in the database:$NS"
    if [[ ! -f $apps_db_file ]]; then
        echo -en "${F_SCR}${ITL}Creating the database file... "
    else
        echo -en "${F_SCR}${ITL}Updating the database... "
    fi

    local data="$app_name"
    if [[ $fake_home_mode == false ]]; then
        for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
            data="${data};${app_dirs_and_files[i]}"
        done
        data="${data};"
    else
        data="${data};FAKEHOME;"
    fi

    echo "$data" >> "$apps_db_file"
    sort -o "$apps_db_file" "$apps_db_file"
    echo -e "$F_OK"

}  # ------------  end of function save_app_info_into_db  ------------



#===  FUNCTION  ================================================================
#         NAME:   Separator
#  DESCRIPTION:   Make a horizontal line that fit the windows width. Also
#                 accept a string as argument then fill the rest of the line.
#    ARGUMENTS:   $1 (optional): A string to add to the horizontal line.
#===============================================================================
function separator()
{
    local sep_char="="
    local max_line_length=""
    # Fix KDE error: <tput: No value for $TERM and no -T specified>
    if [[ -z $TERM || $TERM == "dumb" ]]; then
        max_line_length=1
    else
        max_line_length=$(tput cols)
    fi
    local output=""

    # If no arg, then draw a separation line without text
    if [[ $# -eq 0 ]]; then
        for (( i=0; i<max_line_length; i++ )); do
            output="${output}${sep_char}"
        done
        echo -e "${GREEN}${output}${NS}"
        return
    fi

    #----------------------------------------
    # Build the separator with the argument
    local text="${1^}"
    local out_beginning="${sep_char}${sep_char}${sep_char} "
    local out_middle="${text} Output: "
    local out_current_length=$((${#out_beginning} + ${#out_middle}))
    local remaining_length=$((max_line_length - out_current_length))
    if [[ $remaining_length -lt 3 ]]; then
        # Not enought space to display the text, so we change the output
        out_middle="Program Output: "
        # Also update the remaining length is needed
        out_current_length=$((${#out_beginning} + ${#out_middle}))
        remaining_length=$((max_line_length - out_current_length))
    fi

    # Get the separator horizontal line with the corresponding remaining length
    local out_end=""
    for (( i=0; i<remaining_length; i++ )); do
        out_end="${out_end}${sep_char}"
    done

    # Finally the string can be built
    output="${GREEN}${out_beginning}${NS}${BLD}${out_middle}${NS}"
    output="${output}${GREEN}${out_end}${NS}"

    echo -e "${output}"

}  # ------------  end of function separator  ------------



#===============================================================================
# BEGINNING OF SCRIPT OPERATIONS
#===============================================================================

echo -e "$BLD$SCRIPT_NAME v$SCRIPT_VERSION"
separator

# First read the database.
get_dir_and_files_from_db

#-------------------------------------------------------------------------------
# Fake Home Mode
#-------------------------------------------------------------------------------
if [[ $fake_home_mode == true ]]; then
    echo -e "${F_SCR}${ITL}Running in fake home mode...$NS"
    FORCE_XDG_FOLDER="${FAKE_HOME_FOLDER}"
    HOME="${FAKE_HOME_FOLDER}"

    echo -e "${F_SCR}${ITL}Fake home setted to ${NS}${ORANGE}'${HOME}'$NS"
    if [[ ! -d $HOME ]]; then
        echo -e "${F_SCR}${ITL}${ORANGE}Fake home directory not found.$NS"
        make_data_folder
    fi
    run_app

    if [[ ${#app_dirs_and_files[@]} -eq 0 ]]; then
        save_app_info_into_db
    fi
    echo -e "$F_SCR${ITL}Closing...$NS"
    exit
fi

#-------------------------------------------------------------------------------
# If program data is not found on the db, generate the file and folders list.
# Else, use the data to move the folders to HOME
#-------------------------------------------------------------------------------
if [[ ${#app_dirs_and_files[@]} -eq 0 ]]; then
    # Data not found on db, so we get the diff list of folders/files of home
    home_before=$(get_home_folders_and_files_list)
    run_app
    home_after=$(get_home_folders_and_files_list)
    # Get diff beetwen before and after states.
    # If there are no new files or folders, exit.
    get_home_diff_list

    make_data_folder
    save_app_info_into_db
else
    mv_dirs_and_files_to_home
    trap "interruption_handler" INT
    run_app
    trap - INT
fi

#----------------------------------------
# Cleaning home

mv_dirs_and_files_from_home
echo -e "$F_SCR${ITL}Closing...$NS"
exit

